--<ScriptOptions statementTerminator=";"/>

CREATE TABLE SPRING_BOARD(
B_NUM    NUMBER NOT NULL , 
B_NAME VARCHAR2(10) NOT NULL , 
B_TITLE    VARCHAR2(1000) NOT NULL , 
B_CONTENT CLOB,  B_PWD VARCHAR2(18) NOT NULL , 
B_DATE DATE DEFAULT SYSDATE ) ; 

ALTER TABLE SPRING_BOARD    
ADD CONSTRAINT SPRING_BOARD_PK PRIMARY KEY(B_NUM);

COMMENT ON TABLE     SPRING_BOARD IS '게시판 정보'; 
COMMENT ON COLUMN SPRING_BOARD.B_NUM IS '게시판순번';
COMMENT ON COLUMN SPRING_BOARD.B_NAME IS '게시판작성자'; 
COMMENT ON COLUMN SPRING_BOARD.B_TITLE IS '게시판제목';
COMMENT ON COLUMN SPRING_BOARD.B_CONTENT IS '게시판내용'; 
COMMENT ON COLUMN SPRING_BOARD.B_PWD IS '게시판비밀번호'; 
COMMENT ON COLUMN SPRING_BOARD.B_DATE IS '게시판등록일';

CREATE SEQUENCE SPRING_BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;